version: 2
updates:
  # Maintain dependencies for composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "composer"
      prefix: "[composer]"
